fixed AttributeError: 'NoneType' object has no attribute 'has_key' that was throwed if config was missing
darcs-hash:20081016075453-b2873-b5f1169b2571f47f689bc5d36eb1bd69a0756251.gz